[package]
name = "tokio-postgres"
version = "0.2.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver using Tokio"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://docs.rs/tokio-postgres/0.2.2/tokio_postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[badges]
travis-ci = { repository = "sfackler/rust-postgres" }

[features]
with-bit-vec = ["postgres-shared/with-bit-vec"]
with-chrono = ["postgres-shared/with-chrono"]
with-eui48 = ["postgres-shared/with-eui48"]
with-geo = ["postgres-shared/with-geo"]
with-rustc-serialize = ["postgres-shared/with-rustc-serialize"]
with-serde_json = ["postgres-shared/with-serde_json"]
with-time = ["postgres-shared/with-time"]
with-uuid = ["postgres-shared/with-uuid"]

with-openssl = ["tokio-openssl", "openssl"]

[dependencies]
bytes = "0.4"
fallible-iterator = "0.1.3"
futures = "0.1.7"
futures-state-stream = "0.1"
postgres-protocol = { version = "0.3.0", path = "../postgres-protocol" }
postgres-shared = { version = "0.3.0", path = "../postgres-shared" }
tokio-core = "0.1"
tokio-dns-unofficial = "0.1"
tokio-io = "0.1"

tokio-openssl = { version = "0.1", optional = true }
openssl = { version = "0.9", optional = true }

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.1"
