[package]
name = "tokio-postgres"
version = "0.3.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A native PostgreSQL driver using Tokio"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[package.metadata.docs.rs]
features = [
    "with-bit-vec-0.5",
    "with-chrono-0.4",
    "with-eui48-0.3",
    "with-geo-0.10",
    "with-serde_json-1",
    "with-uuid-0.6",
]

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
"with-bit-vec-0.5" = ["bit-vec-05"]
"with-chrono-0.4" = ["chrono-04"]
"with-eui48-0.4" = ["eui48-04"]
"with-geo-0.10" = ["geo-010"]
with-serde_json-1 = ["serde-1", "serde_json-1"]
"with-uuid-0.7" = ["uuid-07"]

[dependencies]
antidote = "1.0"
bytes = "0.4"
fallible-iterator = "0.1.3"
futures = "0.1.7"
futures-cpupool = "0.1"
log = "0.4"
phf = "0.7.23"
postgres-protocol = { version = "0.3.0", path = "../postgres-protocol" }
state_machine_future = "0.1.7"
tokio-codec = "0.1"
tokio-io = "0.1"
void = "1.0"

bit-vec-05 = { version = "0.5", package = "bit-vec", optional = true }
chrono-04 = { version = "0.4", package = "chrono", optional = true }
eui48-04 = { version = "0.4", package = "eui48", optional = true }
geo-010 = { version = "0.10", package = "geo", optional = true }
serde-1 = { version = "1.0", package = "serde", optional = true }
serde_json-1 = { version = "1.0", package = "serde_json", optional = true }
uuid-07 = { version = "0.7", package = "uuid", optional = true }

[dev-dependencies]
tokio = "0.1.7"
env_logger = "0.5"
