[package]
name = "postgres"
version = "0.10.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/rust-postgres/doc/v0.10.0/postgres"
readme = "README.md"
keywords = ["database", "sql"]
build = "build.rs"

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[build-dependencies]
phf_codegen = "0.7"

[dependencies]
bufstream = "0.1"
byteorder = ">= 0.3, < 0.5"
log = "0.3"
phf = "0.7"
rustc-serialize = "0.3"
net2 = { version = "0.2", features = ["nightly"] }
chrono = { version = "0.2.14", optional = true }
openssl = { version = "0.6.4", optional = true }
serde = { version = "0.3", optional = true } # Delete for 0.11
serde_json = { version = "0.6", optional = true }
time = { version = "0.1.14", optional = true }
unix_socket = { version = ">= 0.3, < 0.5", optional = true, features = ["socket_timeout"] }
uuid = { version = "0.1", optional = true }

[dev-dependencies]
url = "0.2"
