[package]
name = "postgres"
version = "0.11.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/rust-postgres/doc/v0.11.0/postgres"
readme = "README.md"
keywords = ["database", "postgres", "postgresql", "sql"]
build = "build.rs"
include = ["src/*", "build.rs", "Cargo.toml", "LICENSE", "README.md", "THIRD_PARTY"]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[build-dependencies]
phf_codegen = "0.7"

[dependencies]
bufstream = "0.1"
byteorder = ">= 0.3, < 0.5"
log = "0.3"
phf = "0.7"
hex = "0.1"
net2 = "0.2.16"
rustc-serialize = { version = "0.3", optional = true }
chrono = { version = "0.2.14", optional = true }
openssl = { version = ">= 0.6.4, < 0.8", optional = true }
serde_json = { version = "0.6", optional = true }
time = { version = "0.1.14", optional = true }
unix_socket = { version = "0.5", optional = true }
uuid = { version = "0.1", optional = true }
security-framework = { version = "0.1.2", optional = true }
bit-vec = { version = "0.4", optional = true }

[dev-dependencies]
url = "0.5"
