[package]
name = "postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"

[dependencies.phf]
git = "https://github.com/sfackler/rust-phf"

[dependencies.phf_mac]
git = "https://github.com/sfackler/rust-phf"
