version: '2'
services:
  postgres:
    image: docker.io/postgres:17beta2
    ports:
      - 5433:5433
    volumes:
      - ./docker/sql_setup.sh:/docker-entrypoint-initdb.d/sql_setup.sh
    environment:
      POSTGRES_PASSWORD: postgres
