[package]
name = "postgres-protocol"
version = "0.3.2"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Low level Postgres protocol APIs"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/rust-postgres-protocol"
readme = "../README.md"

[dependencies]
base64 = "0.9"
byteorder = "1.0"
bytes = "0.4"
fallible-iterator = "0.1"
generic-array = "0.12"
hmac = "0.7"
md5 = "0.4"
memchr = "2.0"
rand = "0.5"
sha2 = "0.8"
stringprep = "0.1"
