[package]
name = "postgres"
version = "0.17.0-alpha.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A native, synchronous PostgreSQL client"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql"]
categories = ["database"]

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
default = ["runtime"]
runtime = ["tokio-postgres/runtime", "tokio", "lazy_static", "log"]

with-bit-vec-0_6 = ["tokio-postgres/with-bit-vec-0_6"]
with-chrono-0_4 = ["tokio-postgres/with-chrono-0_4"]
with-eui48-0_4 = ["tokio-postgres/with-eui48-0_4"]
with-geo-types-0_4 = ["tokio-postgres/with-geo-types-0_4"]
with-serde_json-1 = ["tokio-postgres/with-serde_json-1"]
with-uuid-0_7 = ["tokio-postgres/with-uuid-0_7"]
with-uuid-0_8 = ["tokio-postgres/with-uuid-0_8"]

[dependencies]
bytes = "0.4"
fallible-iterator = "0.2"
futures-preview = "=0.3.0-alpha.19"
pin-utils = "=0.1.0-alpha.4"
tokio-postgres = { version = "=0.5.0-alpha.1", path = "../tokio-postgres", default-features = false }
tokio-executor = "=0.2.0-alpha.6"

tokio = { version = "=0.2.0-alpha.6", optional = true }
lazy_static = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }

[dev-dependencies]
tokio = "=0.2.0-alpha.6"
