[package]
name = "postgres"
version = "0.15.2"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md", "THIRD_PARTY"]
categories = ["database"]

[package.metadata.docs.rs]
features = [
    "with-bit-vec-0.5",
    "with-chrono-0.4",
    "with-eui48-0.3",
    "with-geo-0.8",
    "with-serde_json-1",
    "with-uuid-0.6",
    "with-openssl",
    "with-native-tls",
]

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[features]
"with-bit-vec-0.5" = ["postgres-shared/with-bit-vec-0.5"]
"with-chrono-0.4" = ["postgres-shared/with-chrono-0.4"]
"with-eui48-0.3" = ["postgres-shared/with-eui48-0.3"]
"with-geo-0.8" = ["postgres-shared/with-geo-0.8"]
"with-serde_json-1" = ["postgres-shared/with-serde_json-1"]
"with-uuid-0.6" = ["postgres-shared/with-uuid-0.6"]

with-openssl = ["openssl"]
with-native-tls = ["native-tls"]
with-schannel = ["schannel"]
with-security-framework = ["security-framework"]

no-logging = []

[dependencies]
bytes = "0.4"
fallible-iterator = "0.1.3"
log = "0.4"
socket2 = { version = "0.3.5", features = ["unix"] }

openssl = { version = "0.9.23", optional = true }
native-tls = { version = "0.1", optional = true }
schannel = { version = "0.1", optional = true }
security-framework = { version = "0.1.2", optional = true }

postgres-protocol = { version = "0.3.0", path = "../postgres-protocol" }
postgres-shared = { version = "0.4.1", path = "../postgres-shared" }

[dev-dependencies]
hex = "0.3"
url = "1.0"

bit-vec = "0.5"
chrono = "0.4"
eui48 = "0.3"
geo = "0.8"
serde_json = "1.0"
uuid = "0.6"
