[package]
name = "postgres"
version = "0.14.2"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://docs.rs/postgres/0.14.2/postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md", "THIRD_PARTY"]
categories = ["database"]

[badges]
travis-ci = { repository = "sfackler/rust-postgres" }

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[features]
with-bit-vec = ["postgres-shared/with-bit-vec"]
with-chrono = ["postgres-shared/with-chrono"]
with-eui48 = ["postgres-shared/with-eui48"]
with-geo = ["postgres-shared/with-geo"]
with-rustc-serialize = ["postgres-shared/with-rustc-serialize"]
with-serde_json = ["postgres-shared/with-serde_json"]
with-time = ["postgres-shared/with-time"]
with-uuid = ["postgres-shared/with-uuid"]

with-openssl = ["openssl"]
with-native-tls = ["native-tls"]
with-schannel = ["schannel"]
with-security-framework = ["security-framework"]

no-logging = []

[dependencies]
bytes = "0.4"
fallible-iterator = "0.1.3"
log = "0.3"

openssl = { version = "0.9.2", optional = true }
native-tls = { version = "0.1", optional = true }
rustc-serialize = { version = "0.3", optional = true }
schannel = { version = "0.1", optional = true }
security-framework = { version = "0.1.2", optional = true }

postgres-protocol = { version = "0.3.0", path = "../postgres-protocol" }
postgres-shared = { version = "0.3.0", path = "../postgres-shared" }

[dev-dependencies]
hex = "0.2"
url = "1.0"

bit-vec = "0.4"
chrono = "0.3"
eui48 = "0.1"
geo = "0.4"
rustc-serialize = "0.3"
serde_json = ">=0.9,<2.0"
time = "0.1.14"
uuid = "0.5"
